"""Build the leaderboard from result files, using recomputed metrics only."""

from __future__ import annotations

from collections.abc import Iterable, Sequence
from pathlib import Path

from .score import TaskMetrics, correct_rows
from .tasks import TaskSpec, benchmark_version, load_rows, load_tasks, question_for
from .verify import Verification, verify_result

__all__ = ["collect", "leaderboard_markdown"]


def collect(
    paths: Iterable[str | Path], *, data_dir: str | Path | None = None
) -> list[Verification]:
    """Verify every ``*.json`` result under ``paths`` (files or directories)."""
    files: list[Path] = []
    for path in paths:
        p = Path(path)
        files += sorted(p.rglob("*.json")) if p.is_dir() else [p]
    return [verify_result(f, data_dir=data_dir) for f in files]


# The overview's number per question kind: its label and the TaskMetrics field.
MAIN = {
    "choice": ("accuracy", "accuracy"),
    "yes_no": ("balanced", "balanced_accuracy"),
    "score": ("within one", "within_one"),
    "extract": ("field F1", "field_f1"),
}


def _pct(value: float | None, digits: int = 1) -> str:
    return "n/a" if value is None else f"{value * 100:.{digits}f}"


def _headline(task: TaskSpec, m: TaskMetrics) -> str:
    """The task-specific second number: the one accuracy alone would hide."""
    if task.kind == "choice":
        return f"macro-F1 {_pct(m.macro_f1)}"
    if task.kind == "yes_no":
        return f"balanced {_pct(m.balanced_accuracy)}"
    if task.kind == "score":
        return (
            "n/a"
            if m.mae_levels is None
            else f"MAE {m.mae_levels:.2f}, within one {_pct(m.within_one)}"
        )
    return f"field F1 {_pct(m.field_f1)}"


def _cost(value: float) -> str:
    return "$0" if value == 0 else f"${value:.3f}"


def _ms(value: float | None) -> str:
    return "n/a" if value is None else f"{value:.0f} ms"


def _locale_breakdown(task: TaskSpec, ranked: Sequence[Verification]) -> list[str]:
    """Accuracy per language, for tasks whose rows carry a locale."""
    rows = load_rows(task, "test")
    locales = {row["id"]: row.get("locale") for row in rows}
    if not any(locales.values()):
        return []
    order = sorted({loc for loc in locales.values() if loc})
    truth = {row["id"]: row["label"] for row in rows}
    question = question_for(task)
    body = []
    for v in sorted(ranked, key=lambda v: v.name.lower()):
        entry = v.result.tasks.get(task.name) if v.result else None
        if entry is None or not entry.supported:
            continue
        predictions = entry.predictions["test"]
        correct = correct_rows(question, predictions, truth)
        cells = []
        for locale in order:
            hits = [
                ok for p, ok in zip(predictions, correct, strict=True) if locales[p["id"]] == locale
            ]
            cells.append(_pct(sum(hits) / len(hits)) if hits else "n/a")
        body.append(f"| {v.name} | " + " | ".join(cells) + " |")
    if not body:
        return []
    header = ["", "Accuracy by language:", "", "| Provider | " + " | ".join(order) + " |"]
    return [*header, "|---|" + "---:|" * len(order), *body]


def leaderboard_markdown(
    verifications: Sequence[Verification], *, verified_dirs: Sequence[str] = ("verified",)
) -> str:
    """Markdown for the leaderboard page.

    A result counts as verified when its path contains one of
    ``verified_dirs`` (maintainers ran it themselves); others are marked as
    submitted. Results that fail
    verification or are partial are listed separately and not ranked.
    """
    tasks = load_tasks()
    ranked = [v for v in verifications if v.rankable]
    rejected = [v for v in verifications if not v.rankable]

    def label(v: Verification) -> str:
        trained = v.result is not None and v.result.submission.trained_on_task_data
        return f"{v.name} (trained on task data)" if trained else v.name

    def origin(v: Verification) -> str:
        parts = Path(v.path).parts
        return "verified" if any(d in parts for d in verified_dirs) else "submitted"

    lines = [
        f"<!-- generated by `fastbrain bench decisions leaderboard`; benchmark {benchmark_version()} -->",
        "",
        "## Overview",
        "",
        "Each task's main metric on its test rows, in percent: accuracy for choice questions, "
        "balanced accuracy for yes or no questions, accuracy within one level for scores, and "
        "field F1 for extraction. In parentheses: the share of rows the provider can answer on "
        "its own at 95 percent accuracy, with the threshold fitted on the calibration rows (only "
        "for providers that report a confidence). `n/a`: the provider does not answer this kind "
        "of question. Status: `verified` runs were done by the maintainers; `submitted` runs "
        "were sent in by others and checked by CI.",
        "",
        "| Provider | Status | "
        + " | ".join(f"{t.name} ({MAIN[t.kind][0]})" for t in tasks)
        + " |",
        "|---|---|" + "---:|" * len(tasks),
    ]
    for v in sorted(ranked, key=lambda v: v.name.lower()):
        cells = []
        for t in tasks:
            m = v.metrics.get(t.name)
            if m is None:
                cells.append("n/a")
                continue
            cell = _pct(getattr(m, MAIN[t.kind][1]))
            if m.coverage is not None:
                cell += f" ({_pct(m.coverage, 0)})"
            cells.append(cell)
        lines.append(f"| {label(v)} | {origin(v)} | " + " | ".join(cells) + " |")

    for t in tasks:
        lines += [
            "",
            f"## {t.name}",
            "",
            f"{t.title}. {t.notes}",
            "",
            "| Provider | Accuracy (95% CI) | Task metric | ECE | Coverage at 95% | Accuracy there | AURC | p50 | Cost per 1k |",
            "|---|---:|---:|---:|---:|---:|---:|---:|---:|",
        ]
        rows = [(v, v.metrics[t.name]) for v in ranked if t.name in v.metrics]
        for v, m in sorted(rows, key=lambda item: -item[1].accuracy):
            lines.append(
                f"| {v.name} | {_pct(m.accuracy)} ({_pct(m.accuracy_low)} to {_pct(m.accuracy_high)}) "
                f"| {_headline(t, m)} | {'n/a' if m.ece is None else f'{m.ece:.3f}'} "
                f"| {_pct(m.coverage)} | {_pct(m.selective_accuracy)} "
                f"| {'n/a' if m.aurc is None else f'{m.aurc:.3f}'} "
                f"| {_ms(m.latency_p50_ms)} | {_cost(m.cost_per_1k_usd)} |"
            )
        lines += _locale_breakdown(t, ranked)
        missing = [v.name for v in ranked if t.name not in v.metrics]
        if missing:
            lines += [
                "",
                "Not answered (question kind unsupported): " + ", ".join(sorted(missing)) + ".",
            ]

    lines += [
        "",
        "## Runs",
        "",
        "| Provider | Spec | Model | Hardware | FastBrain | Date | Notes |",
        "|---|---|---|---|---|---|---|",
    ]
    for v in sorted(ranked, key=lambda v: v.name.lower()):
        r = v.result
        assert r is not None
        lines.append(
            f"| {v.name} | `{r.submission.spec}` | {r.submission.model or 'n/a'} "
            f"| {r.environment.get('device', 'n/a')} | {r.fastbrain_version} | {r.created_at[:10]} "
            f"| {(r.submission.notes or '').replace('|', '/')} |"
        )
    if rejected:
        lines += ["", "## Not ranked", ""]
        for v in rejected:
            reason = "; ".join(v.problems + v.notes) or "not rankable"
            lines.append(f"- `{Path(v.path).name}` ({v.name}): {reason}")
    return "\n".join(lines) + "\n"
